"""initial

Revision ID: 0b56dde28e07
Revises: 
Create Date: 2026-02-28 16:23:21.705357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b56dde28e07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_ward'), 'users', ['ward'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('is_merged', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('priority_label', sa.String(), nullable=True),
    sa.Column('reports_count', sa.Integer(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('assigned_department', sa.String(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_similarity_score', sa.Float(), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expected_resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_assigned_department'), 'complaints', ['assigned_department'], unique=False)
    op.create_index(op.f('ix_complaints_assigned_to'), 'complaints', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_citizen_id'), 'complaints', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_complaints_escalation_level'), 'complaints', ['escalation_level'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_is_merged'), 'complaints', ['is_merged'], unique=False)
    op.create_index(op.f('ix_complaints_is_sla_breached'), 'complaints', ['is_sla_breached'], unique=False)
    op.create_index(op.f('ix_complaints_merged_into_id'), 'complaints', ['merged_into_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority_label'), 'complaints', ['priority_label'], unique=False)
    op.create_index(op.f('ix_complaints_title'), 'complaints', ['title'], unique=False)
    op.create_index(op.f('ix_complaints_ward'), 'complaints', ['ward'], unique=False)
    op.create_table('complaint_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_activities_actor_id'), 'complaint_activities', ['actor_id'], unique=False)
    op.create_index(op.f('ix_complaint_activities_complaint_id'), 'complaint_activities', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_activities_id'), 'complaint_activities', ['id'], unique=False)
    op.create_table('complaint_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_updates_complaint_id'), 'complaint_updates', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_updates_id'), 'complaint_updates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_updates_id'), table_name='complaint_updates')
    op.drop_index(op.f('ix_complaint_updates_complaint_id'), table_name='complaint_updates')
    op.drop_table('complaint_updates')
    op.drop_index(op.f('ix_complaint_activities_id'), table_name='complaint_activities')
    op.drop_index(op.f('ix_complaint_activities_complaint_id'), table_name='complaint_activities')
    op.drop_index(op.f('ix_complaint_activities_actor_id'), table_name='complaint_activities')
    op.drop_table('complaint_activities')
    op.drop_index(op.f('ix_complaints_ward'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_title'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority_label'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_merged_into_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_is_sla_breached'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_is_merged'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_escalation_level'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_citizen_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_to'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_department'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_ward'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
