"""Add ComplaintUpvote

Revision ID: 405ceaa69792
Revises: 8d337dc5d6be
Create Date: 2026-03-03 08:58:24.362045

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "405ceaa69792"
down_revision: Union[str, None] = "8d337dc5d6be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaint_upvotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complaint_upvotes_complaint_id"),
        "complaint_upvotes",
        ["complaint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaint_upvotes_id"), "complaint_upvotes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_complaint_upvotes_user_id"),
        "complaint_upvotes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_complaint_upvotes_user_id"), table_name="complaint_upvotes")
    op.drop_index(op.f("ix_complaint_upvotes_id"), table_name="complaint_upvotes")
    op.drop_index(
        op.f("ix_complaint_upvotes_complaint_id"), table_name="complaint_upvotes"
    )
    op.drop_table("complaint_upvotes")
    # ### end Alembic commands ###
