"""initial

Revision ID: 6a436e95340f
Revises:
Create Date: 2026-02-27 20:38:10.135703

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a436e95340f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaint_activities", sa.Column("previous_value", sa.String(), nullable=True)
    )
    op.add_column(
        "complaint_activities", sa.Column("new_value", sa.String(), nullable=True)
    )
    op.add_column(
        "complaints", sa.Column("ai_confidence_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "complaints", sa.Column("ai_similarity_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "complaints", sa.Column("is_sla_breached", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "complaints", sa.Column("escalation_level", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_complaints_escalation_level"),
        "complaints",
        ["escalation_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_complaints_is_sla_breached"),
        "complaints",
        ["is_sla_breached"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_complaints_is_sla_breached"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_escalation_level"), table_name="complaints")
    op.drop_column("complaints", "escalation_level")
    op.drop_column("complaints", "is_sla_breached")
    op.drop_column("complaints", "ai_similarity_score")
    op.drop_column("complaints", "ai_confidence_score")
    op.drop_column("complaint_activities", "new_value")
    op.drop_column("complaint_activities", "previous_value")
    # ### end Alembic commands ###
