"""Add department to user

Revision ID: 829bd1d77553
Revises: 405ceaa69792
Create Date: 2026-03-03 11:05:07.779542

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "829bd1d77553"
down_revision: Union[str, None] = "405ceaa69792"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("department", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_department"), "users", ["department"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_department"), table_name="users")
    op.drop_column("users", "department")
    # ### end Alembic commands ###
