"""add_photo_url_and_assigned_at

Revision ID: 8d337dc5d6be
Revises: 0b56dde28e07
Create Date: 2026-02-28 17:31:39.891848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d337dc5d6be'
down_revision: Union[str, None] = '0b56dde28e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'assigned_at')
    op.drop_column('complaints', 'photo_url')
    # ### end Alembic commands ###
