"""Add is_suspended to users

Revision ID: e1efebb72f35
Revises: 829bd1d77553
Create Date: 2026-03-04 00:14:46.828273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1efebb72f35'
down_revision: Union[str, None] = '829bd1d77553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    # ### end Alembic commands ###
