"""add incident_ward to complaints

Revision ID: e949afcd2476
Revises: e1efebb72f35
Create Date: 2026-03-04 10:36:23.026969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e949afcd2476'
down_revision: Union[str, None] = 'e1efebb72f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('incident_ward', sa.String(), nullable=True))
    op.create_index(op.f('ix_complaints_incident_ward'), 'complaints', ['incident_ward'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_incident_ward'), table_name='complaints')
    op.drop_column('complaints', 'incident_ward')
    # ### end Alembic commands ###
